controle_acesso/urls.py
from django.urls import path
from . import views
from .views import CustomPasswordChangeView

urlpatterns = [
    path('', views.index, name='controle_acesso_index'),
    path('cadastro/', views.cadastro_usuario, name='cadastro_usuario'),
    path('usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('perfil/', views.user_profile, name='perfil'),
    path('perfil/editar/', views.edit_profile, name='edit_profile'),
    path('check-password-change/', views.check_password_change, name='check_password_change'),
    path('trocar-senha/', CustomPasswordChangeView.as_view(), name='change_password'),
    path('historico-atividades/',views.activity_log_view, name='user_activity_list'),
    path('set_group/<int:user_id>/', views.set_group, name='set_group'),
]

dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='dashboard_index'),  # Página inicial do dashboard
]

security_wayne/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('admin/', admin.site.urls),
    path('acesso/', include('controle_acesso.urls')),
    path('recursos/', include('gestao_recursos.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='controle_acesso/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'),name='logout')
    
]

controle_acesso/models.py
# models.py

from django.db import models
from django.contrib.auth.models import User



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    must_change_password = models.BooleanField(default=True)  # Indica se o usuário precisa mudar a senha

class UserActivity(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    action = models.CharField(max_length=10, choices=[('login', 'Login'),('logout','Logout')])
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user.username} - {self.action} at {self.timestamp}"

controle_acesso/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.contrib.auth import get_user_model

class GerenteCadastroForm(UserCreationForm):
    groups = forms.ModelMultipleChoiceField(
        queryset=Group.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required= False
    )
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields= ['username','email','password1','password2','groups']
    
    def save(self, commit=True):
        user = super(GerenteCadastroForm, self).save(commit=False)
        if commit:
            user.save()
            # Após salvar o usuário, crie o perfil e defina must_change_password como True
            profile = Profile.objects.create(user=user)
            user.groups.set(self.cleaned_data['groups'])
            profile.must_change_password = True
            profile.save()
        return user

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


User = get_user_model()

class SetGroupForm(forms.Form):
    group = forms.ModelChoiceField(queryset=Group.objects.filter(name__in=['Segurança', 'Serviços gerais']), required=True)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def save(self):
        # Remove o usuário de ambos os grupos antes de atribuir o novo
        self.user.groups.clear()
        self.user.groups.add(self.cleaned_data['group'])

controle_acesso/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from .forms import GerenteCadastroForm, EditProfileForm, SetGroupForm
from .models import Profile, UserActivity
from django.views.generic import ListView
from django.core.paginator import Paginator


# Função de view para a página inicial
def index(request):
    return render(request, 'controle_acesso/index.html')

# Funções para validação de acesso
def is_admin(user):
    return user.is_superuser

def is_manager_adm(user):
    return user.is_superuser or user.groups.filter(name='Gerente').exists()

# Cadastro de usuário para administradores
@login_required
@user_passes_test(is_admin, login_url='/acesso')
def cadastro_usuario(request):
    if request.method == 'POST':
        form = GerenteCadastroForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_usuarios')
    else:
        form = GerenteCadastroForm()
    return render(request, 'controle_acesso/cadastro_usuario.html', {'form': form})

# Lista de usuários para administradores e gerentes
@login_required
@user_passes_test(is_manager_adm)
def lista_usuarios(request):
    usuarios = User.objects.all()
    return render(request, 'controle_acesso/lista_usuarios.html', {'usuarios': usuarios})

# Edição de perfil de usuário
@login_required
def edit_profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('perfil')
    else:
        form = EditProfileForm(instance=request.user)
    return render(request, 'controle_acesso/edit_profile.html', {'form': form})

# Visualização do perfil do usuário
@login_required
def user_profile(request):
    return render(request, 'controle_acesso/user_profile.html', {'user': request.user})

# Verificação para redirecionar se a senha precisa ser trocada
@login_required
def check_password_change(request):
    if request.user.is_superuser:
        return redirect('perfil')  # Superuser vai direto para o perfil
    elif request.user.profile.must_change_password:
        return redirect('change_password')  # Outros usuários com `must_change_password=True` são redirecionados para trocar a senha
    else:
        return redirect('perfil')

# View customizada de troca de senha com atualização de status de troca
class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'controle_acesso/change_password.html'
    success_url = reverse_lazy('perfil')

    def form_valid(self, form):
        response = super().form_valid(form)
        # Atualiza o campo must_change_password
        self.request.user.profile.must_change_password = False
        self.request.user.profile.save()
        return response


# class UserActivityListView(ListView):
#     model = UserActivity
#     template_name = 'controle_acesso/user_activity_list.html'
#     context_object_name = 'activities'
#     ordering = ['-timestamp']
#     paginate_by = 10
@login_required
@user_passes_test(is_admin)
def activity_log_view(request):
    activities_list = UserActivity.objects.select_related('user').order_by('-timestamp')
    paginator = Paginator(activities_list, 10)  # Mostra 10 atividades por página

    page_number = request.GET.get('page')
    activities = paginator.get_page(page_number)

    return render(request, 'controle_acesso/user_activity_list.html', {'activities': activities})

@login_required
@user_passes_test(is_manager_adm)
def set_group(request, user_id):
    user = User.objects.get(id=user_id)
    
    if request.method == 'POST':
        form = SetGroupForm(request.POST, user=user)
        if form.is_valid():
            form.save()
            return redirect('lista_usuarios')
    else:
        form = SetGroupForm(user=user)
    
    return render(request, 'controle_acesso/set_group.html', {'form': form, 'user': user})

controle_acesso/templates/controle_acesso/cadastro_usuario.html
{% extends 'base.html' %}

{% block title %}Cadastrar Usuário{% endblock %}

{% block content %}
<div class="bg-black p-6 rounded-lg shadow-lg text-gray-500 max-w-md mx-auto">
    <h2 class="text-2xl font-bold text-yellow-500 mb-4">Cadastrar Novo Usuário</h2>

    <form method="post" class="space-y-4">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="w-full bg-yellow-500 text-gray-800 font-semibold py-2 px-4 rounded-lg hover:bg-yellow-400 transition duration-300">
            Cadastrar
        </button>
    </form>
</div>
{% endblock %}

controle_acesso/templates/controle_acesso/change_password.html
{% extends "base.html" %}

{% block content %}
<div class="bg-black p-6 rounded-lg shadow-lg text-gray-500 max-w-md mx-auto">
    <h1 class="text-2xl font-bold text-yellow-500 mb-4">Trocar Senha</h1>

    <form method="post" class="space-y-4">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="w-full bg-yellow-500 text-gray-800 font-semibold py-2 px-4 rounded-lg hover:bg-yellow-400 transition duration-300">
            Salvar nova senha
        </button>
    </form>
</div>
{% endblock %}

controle_acesso/templates/controle_acesso/edit_profile.html
{% extends "base.html" %}

{% block content %}
<div class="bg-black p-6 rounded-lg shadow-lg text-gray-500 max-w-md mx-auto">
    <h1 class="text-2xl font-bold text-yellow-500 mb-4">Editar Perfil</h1>

    <form method="post" class="space-y-4">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Renderiza o formulário -->

        <button type="submit" class="w-full bg-yellow-500 text-gray-800 font-semibold py-2 px-4 rounded-lg hover:bg-yellow-400 transition duration-300">
            Salvar
        </button>
    </form>

    <a href="{% url 'perfil' %}" class="block text-yellow-500 hover:text-yellow-400 mt-4 text-center">
        Cancelar
    </a>
</div>
{% endblock %}

controle_acesso/templates/controle_acesso/index.html
{% extends "base.html" %}
{% load custom_tags %}
{% block title %}Acesso ao Sistema{% endblock %}

{% block content %}
    <h2 class="text-3xl font-semibold text-yellow-500 mb-4">Bem-vindo ao Controle de Acesso</h2>

    {% if user.is_authenticated %}
        <p class="text-lg text-gray-400 mb-4">Você está logado como <span class="font-semibold">{{ user.username }}</span>.</p>

        <div class="space-y-2">
            {% if user.is_superuser %}
                <p>
                    <a href="{% url 'cadastro_usuario' %}" class="text-yellow-500 hover:text-yellow-400 underline">
                        Cadastrar Novo Usuário
                    </a>
                </p>
                <p>
                    <a href="{% url 'lista_usuarios' %}" class="text-yellow-500 hover:text-yellow-400 underline">
                        Lista de Usuários
                    </a>
                </p>
                <p>
                    <a href="{% url 'user_activity_list' %}" class="text-yellow-500 hover:text-yellow-400 underline">
                        Entrada e Saída de Funcionários
                    </a>
                </p>
            {% elif user|in_group:"Gerente" %}
                <p>
                    <a href="{% url 'lista_usuarios' %}" class="text-yellow-500 hover:text-yellow-400 underline">
                        Lista de Usuários
                    </a>
                </p>
            {% else %}
                <p class="text-red-500 font-semibold">Você não possui acesso a essas áreas.</p>
            {% endif %}
        </div>
    {% else %}
        <p class="text-lg text-gray-400">
            Por favor, <a href="{% url 'login' %}" class="text-yellow-500 hover:text-yellow-400 underline">faça login</a> para acessar o sistema.
        </p>
    {% endif %}
{% endblock %}

controle_acesso/templates/controle_acesso/lista_usuarios.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block title %}Lista de Usuários{% endblock %}

{% block content %}
    <h2 class="text-3xl font-semibold text-yellow-500 mb-6">Lista de Usuários</h2>
    
    <ul class="bg-gray-800 p-4 rounded-lg shadow-md space-y-3">
        {% for usuario in usuarios %}
            <li class="flex justify-between items-center p-3 bg-gray-700 rounded-md text-gray-300">
                <div class="flex flex-col">
                    <span class="font-semibold">{{ usuario.username }}</span>
                    <span>{{ usuario.email }}</span>
                </div>
                
                <span class="text-yellow-500">
                    {% if usuario.groups.all %}
                        {{ usuario.groups.first.name }}
                    {% else %}
                        {% if usuario.is_superuser %} Admin {% else %} Sem função atribuída {% endif %}
                    {% endif %}
                </span>
                
                {% if usuario|in_group:"Funcionarios" or usuario|in_group:"Segurança" or usuario|in_group:"Serviços gerais" %}
                    <a href="{% url 'set_group' usuario.id %}" class="ml-4 px-3 py-2 bg-blue-500 hover:bg-blue-600 text-white text-sm font-semibold rounded-md shadow">
                        Definir Função
                    </a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

controle_acesso/templates/controle_acesso/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="flex items-center justify-center min-h-screen bg-gray-900">
    <div class="w-full max-w-md p-8 bg-black rounded-lg shadow-lg">
        <h2 class="text-2xl font-bold text-yellow-500 text-center mb-6">Entrar no Sistema</h2>
        
        <form method="post" class="space-y-6">
            {% csrf_token %}
            
            <div class="space-y-4">
                {{ form.as_p }}
            </div>
            
            <button type="submit" class="w-full py-2 bg-yellow-500 text-gray-800 font-semibold rounded-md hover:bg-yellow-400 focus:outline-none focus:ring-2 focus:ring-yellow-500 transition duration-300">
                Entrar
            </button>
        </form>
    </div>
</div>
{% endblock %}

controle_acesso/templates/controle_acesso/set_group.html
<!-- set_group.html -->
{% extends "base.html" %}

{% block content %}
  <h2>Definir Função para {{ user.username }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
  </form>
  <a href="{% url 'lista_usuarios' %}">Voltar para a lista de usuários</a>
{% endblock %}

controle_acesso/templates/controle_acesso/user_activity_list.html
{% extends "base.html" %}

{% block title %}Histórico de Login e Logout{% endblock %}

{% block content %}
    <h1 class="text-3xl font-semibold text-yellow-500 mb-6">Histórico de Login e Logout dos Usuários</h1>

    <table class="min-w-full bg-gray-800 rounded-lg shadow-lg">
        <thead>
            <tr class="bg-gray-700 text-yellow-500">
                <th class="py-2 px-4 text-left">Usuário</th>
                <th class="py-2 px-4 text-left">Ação</th>
                <th class="py-2 px-4 text-left">Data e Hora</th>
            </tr>
        </thead>
        <tbody>
            {% for activity in activities %}
                <tr class="border-b border-gray-600 text-gray-300">
                    <td class="py-2 px-4">{{ activity.user.username }}</td>
                    <td class="py-2 px-4">{{ activity.get_action_display }}</td>
                    <td class="py-2 px-4">{{ activity.timestamp|date:"d/m/Y H:i" }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3" class="py-4 px-4 text-center text-gray-400">Nenhuma atividade encontrada.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Paginação -->
    <div class="mt-4 flex justify-center items-center text-gray-400">
        <span class="mx-2">
            Página {{ activities.number }} de {{ activities.paginator.num_pages }}
        </span>

        {% if activities.has_previous %}
            <a href="?page=1" class="mx-1 text-yellow-500 hover:text-yellow-400">Primeira</a>
            <a href="?page={{ activities.previous_page_number }}" class="mx-1 text-yellow-500 hover:text-yellow-400">Anterior</a>
        {% endif %}

        {% if activities.has_next %}
            <a href="?page={{ activities.next_page_number }}" class="mx-1 text-yellow-500 hover:text-yellow-400">Próxima</a>
            <a href="?page={{ activities.paginator.num_pages }}" class="mx-1 text-yellow-500 hover:text-yellow-400">Última</a>
        {% endif %}
    </div>
{% endblock %}

controle_acesso/templates/controle_acesso/user_profile.html
{% extends "base.html" %}
{% block title %}Perfil de {{ user.username }}{% endblock %}

{% block content %}
<div class="bg-gray-800 p-6 rounded-lg shadow-lg text-gray-300 max-w-md mx-auto">
    <h2 class="text-2xl font-bold text-yellow-500 mb-4">Perfil de {{ user.username }}</h2>

    <p><strong>Nome de usuário:</strong> {{ user.username }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p>

    {% if user.first_name or user.last_name %}
        <p><strong>Nome Completo:</strong> {{ user.first_name }} {{ user.last_name }}</p>
    {% endif %}

    <p><strong>Cargo:</strong> 
        {% if user.groups.all %}
            {{ user.groups.first.name }}
        {% else %}
            {% if user.is_superuser %}
                Admin
            {% else %}
                Funcionario
            {% endif %}
        {% endif %}
    </p>

    <!-- Links para edição do perfil e troca de senha -->
    <div class="mt-4">
        <a href="{% url 'edit_profile' %}" class="block text-yellow-500 hover:text-yellow-400">Editar Perfil</a>
        <a href="{% url 'change_password' %}" class="block text-yellow-500 hover:text-yellow-400">Trocar Senha</a>
    </div>
</div>
{% endblock %}